import fs from 'node:fs/promises';
import {PresentationFile,FileBlob} from '@oai/artifact-tool';
import {finalizePresentation} from '/Users/me/.codex/plugins/cache/openai-primary-runtime/presentations/26.909.12148/skills/presentations/container_tools/artifact_tool_utils.mjs';
const p=await PresentationFile.importPptx(await FileBlob.load('subset.pptx'));
const slides=p.slides.items;
function set(i,id,text,size){const x=slides[i].shapes.items.find(x=>x.id===id);if(!x)throw Error(id);x.text=text;if(size)x.text.style={typeface:'Arial',fontSize:size,color:'#FFFFFF',autoFit:'none'};return x;}
set(0,'4','Astra-IFC-\nComplience',76);set(0,'5','AI-assisted model review\nFor modeling and cost estimation teams',26);set(0,'6','Hackathon project demo',24);
set(1,'533','Model data review before estimation',48);set(1,'7','Modeling teams\n\nCheck an object’s identity and properties in its 3D context.\n\nResolve missing or inconsistent information before handing the model to estimators.',29);set(1,'8','Cost estimation teams\n\nReview which elements belong in the estimate.\n\nInspect classifications and export the filtered element list for further work.',29);
set(2,'533','The current workspace',44).position={left:41,top:36,width:580,height:110};set(2,'532','3',16).position={left:1184,top:659,width:55,height:26};set(2,'8','A connected view of the model\n\nSelect an element in the tree, 3D scene, or data sheet.\n\nInspect its properties, zoom in, or isolate it for review.\n\nThe bundled sample loads 483 elements.',28);
let im=slides[2].images.items[0];im.replace({blob:await fs.readFile('workspace.png'),contentType:'image/png',alt:'Actual Forma workspace showing the sample IFC model',fit:'contain'});
set(3,'3','AI-assisted mapping and compliance',48);set(3,'10','1. Read the standard\nUse the supplied ASTM UniFormat workbook as the reference for mapping.',27);set(3,'11','2. Propose a mapping\nAI suggests a classification using the object’s properties and context.',27);set(3,'4','3. Review the evidence\nAsk why the mapping fits and identify missing data before accepting it.',27);set(3,'5','4. Confirm and update\nA modeler approves the mapping before updating the model data.',27);set(3,'6','Target workflow. AI mapping and write-back are not implemented in this repo.',19).position={left:41,top:635,width:1080,height:40};set(3,'2','4',16);
set(4,'533','Astra: intended hackathon use',48);set(4,'534','GPT-Live-1\n\nDiscuss the current model through natural conversation while keeping the selected object in context.',27);set(4,'3','Visual Understanding\n\nConnect questions about the visible 3D scene with IFC element properties and review evidence.',27);set(4,'2','Agents API\n\nUse model tools to inspect properties, change the view, and prepare an issue for human review.',27);set(4,'532','5',16);set(4,'4','Live model and Agents API integration are not verified in this repository.',19).position={left:41,top:650,width:1100,height:40};
let agenda=slides[5].shapes.items;for(let x of agenda){const t=x.text.toString();if(t==='Today’s Agenda')x.text='Live demo sequence';if(t==='3')x.text='6';const a=['Open the sample IFC model','Select an object and inspect properties','Ask about the selected element','Isolate it and inspect the 3D view','Draft a review issue and save its viewpoint','Filter the data sheet and export Excel'];const old=['Agenda item one','Agenda item two','Agenda item three','Agenda item four','Agenda item five','Agenda item six'];if(old.includes(t))x.text=a[old.indexOf(t)];}
set(6,'533','Prototype status and next steps',48);set(6,'5','Working today\n\nIFC import, linked selection, scene controls, Excel export, and local review issues.',27);set(6,'6','Tool foundation\n\n10 WebMCP tools expose model data, scene state, measurements, and issue actions.',27);set(6,'7','Next integration\n\nConnect live Astra, add standards reasoning, and persist approved mappings.',27);set(6,'532','7',16);
set(7,'4','Model review with\nvisible evidence',72);set(7,'5','Astra-IFC-Complience\nQuestions and live demo',26).position={left:41,top:522,width:850,height:115};set(7,'6','Thank you',24);
const notes=[
'Opening, 20 seconds: Astra-IFC-Complience helps modeling and cost estimation teams inspect building model entities and review the data behind them. We aim to combine model conversation with standards-based mapping and compliance review. Preserve the project name as supplied. Sources: user project brief. Cover photo retained from the chosen Simple Dark Mode template.',
'Problem, 25 seconds: Focus on the handoff between modelers and estimators. The goal is to make it easier to establish what an element is and whether its data is suitable for downstream work. Do not claim measured time or cost savings. Sources: user brief; frontend/src/lib/model.ts; frontend/src/App.tsx.',
'Product, 30 seconds: The application currently uses the Forma name in its interface. Show that the tree, geometry, and sheet refer to the same element. Zoom and isolate help investigate it. Source: actual screenshot captured from localhost on 13 September 2026; frontend/src/App.tsx; frontend/src/lib/viewer.ts. 483 elements appeared in the sample during this capture.',
'Target workflow, 30 seconds: Describe this as the planned AI mapping workflow. The repository contains assets/ASTM-UniFormat.xlsx, but the current frontend does not implement standard ingestion, AI classification updates, or model write-back. A classification mapping is not itself proof of regulatory compliance. Compliance conclusions need the applicable requirement and supporting property evidence. Sources: user brief; assets/ASTM-UniFormat.xlsx; frontend/src/lib/model.ts.',
'Astra, 30 seconds: These correspond to the requested categories: Best use of GPT-Live-1, Best example of Visual Understanding, and Best use of Agents API. This slide describes intended use, not award wins. The repository has browser tool registration, but it does not establish a direct GPT-Live-1 or Agents API connection. Built-in chat uses mock responses and browser speech. If a separate external Astra session is used for judging, demonstrate that session. Sources: frontend/src/lib/webmcp.ts; frontend/src/components/ChatPanel.tsx; frontend/src/mock-api/index.ts; frontend/README.md.',
'Live demo, approximately 90 seconds: Open Sample model. Select a wall from the model tree. Inspect its properties. Ask Tell me about the selected element. Type Isolate selected element to demonstrate the local command. Restore with Show all. Use Draft an issue, enter a meaningful title, review it, and save. Reopen the saved issue to restore its viewpoint. Filter the sheet and choose Export .xlsx. General chat answers are mocked, so do not present them as live Astra reasoning. Sources: frontend/src/lib/review.ts; frontend/src/components/ChatPanel.tsx; frontend/src/lib/model.ts.',
'Status, 25 seconds: The review tool layer exposes ten tools. It registers when the browser provides modelContext and otherwise falls back to local tools. Measurement returns approximate world-axis bounding boxes in metres, not exact quantities for estimating. Review issues persist in browser local storage. Next work includes live model integration, standard-backed reasoning, and approved mapping persistence. Sources: frontend/src/lib/webmcp.ts; frontend/src/lib/review.ts; frontend/README.md.',
'Close, 15 seconds: Our focus is helping modelers and estimators inspect the same objects and review the same evidence. Invite questions about the live model, tool actions, and standards mapping workflow. Source: user project brief.'
];
for(let i=0;i<slides.length;i++){slides[i].speakerNotes.textFrame.setText(notes[i]);await fs.writeFile(`slide-${i+1}.png`,new Uint8Array(await (await slides[i].export({format:'png',scale:1})).arrayBuffer()));}
await (await PresentationFile.exportPptx(p)).save('candidate.pptx');
const root='/Users/me/Downloads/repos/hackathon-openai-astra/marketing',skill='/Users/me/.codex/plugins/cache/openai-primary-runtime/presentations/26.909.12148/skills/presentations';
await finalizePresentation({workspaceDir:root,candidatePath:root+'/.build/candidate.pptx',finalPath:root+'/output/Astra-IFC-Complience.pptx',pythonExecutable:'/Users/me/.cache/codex-runtimes/codex-primary-runtime/dependencies/python/bin/python3',integrityValidatorPath:skill+'/container_tools/inspect_presentation_package_integrity.py',layoutValidatorPath:skill+'/container_tools/inspect_presentation_layout_geometry.py',layoutArgs:['--expected-slide-size-emu','12192000,6858000','--validate-heading-fit'],verifyArtifactToolImport:true,receiptPath:root+'/.build/validation-final.json'});
