import fs from 'node:fs/promises';import {PresentationFile,FileBlob} from '@oai/artifact-tool';
import {finalizePresentation} from '/Users/me/.codex/plugins/cache/openai-primary-runtime/presentations/26.909.12148/skills/presentations/container_tools/artifact_tool_utils.mjs';
const root='/Users/me/Downloads/repos/hackathon-openai-astra';
const p=await PresentationFile.importPptx(await FileBlob.load(root+'/assets/Astra-IFC-Complience-Comparison.pptx'));
const original=[...p.slides.items];
const rename=t=>t.replace(/Astra-IFC-\s*Compli(?:e|a)nce/gi,'Forma').replace(/Astra I F C Compliance/g,'Forma').replace(/Chuongpvn@gmail.com/gi,'chuongpqvn@gmail.com');
for(const s of original){for(const a of s.shapes.items){const t=a.text.toString(),v=rename(t);if(t!==v)a.text=v;}s.speakerNotes.textFrame.setText(rename(s.speakerNotes.textFrame.toString()));}
function set(s,id,t,size){const a=s.shapes.items.find(a=>a.id===id);a.text=t;if(size)a.text.style={typeface:'Arial',fontSize:size,color:'#FFFFFF',autoFit:'none'};return a;}
function txt(s,t,x,y,w,h,size=28){let a=s.shapes.add({geometry:'textbox',position:{left:x,top:y,width:w,height:h},fill:'none',line:{fill:'none',width:0}});a.text=t;a.text.style={typeface:'Arial',fontSize:size,color:'#FFFFFF',autoFit:'none'};return a;}
set(original[0],'4','Forma',92);set(original[0],'5','Visual compliance review for building model data\nUse cases, pain points, and the solution',25);
set(original[1],'533','The problem: model data is hard to verify',46);
set(original[1],'7','A building can look right\nwhile its data is wrong\n\nMissing or incorrect classifications make it harder to understand what each element represents.',31);
set(original[1],'8','Review happens across\nseparate tools\n\nModelers compare geometry, properties, and standards by hand. Estimators need the same information for a reliable handoff.',31);
original[1].speakerNotes.textFrame.setText('Pain points, 35 seconds. A visually convincing building model can still contain missing or mismatched classifications. Reviewers need to reconcile object identity, location, and the standard reference. Explain these as target user problems, not measured error rates. Estimators depend on consistent element categories for downstream work. Sources: user project brief; ASTM-UniFormat.xlsx Instructions A2 and ASTM 2015 A7:H7.');
const {slide:use}=p.slides.insert({after:original[1]});use.background.fill='#000000';txt(use,'Who Forma helps',41,36,1198,85,48);
const cases=[['Architects and modelers','Check an object’s classification','Inspect a window in 3D, compare its label with the reference, and review a suggested correction.'],['Design reviewers','Find missing or mismatched data','Locate the affected element and keep the finding with a saved viewpoint.'],['Cost estimation teams','Prepare a consistent element list','Review the model data, filter the relevant elements, and export the list to Excel.']];
for(let i=0;i<3;i++){let x=41+i*411;txt(use,cases[i][0],x,200,375,70,30);txt(use,cases[i][1],x,300,375,90,30);txt(use,cases[i][2],x,420,375,165,27);}
txt(use,'Classification suggestions and approved model updates are the development target.',41,650,1140,40,19);
use.speakerNotes.textFrame.setText('Use cases, 35 seconds. Walk through three users: architects identify and correct object data, reviewers record traceable findings, and estimators reuse filtered element lists. Current prototype supports visual inspection, local review issues and export. AI classification checks and write-back are planned.');
set(original[3],'3','The solution: check each object in context',46);set(original[3],'10','1. Identify the building part\nSelect a wall, window, or door and inspect its model properties.',27);set(original[3],'11','2. Compare its classification\nUse the selected UniFormat edition to find the appropriate code and description.',27);set(original[3],'4','3. Explain the mismatch\nShow the current label beside the suggested classification and its reference.',27);set(original[3],'5','4. Review the correction\nThe designer confirms the match before changing the model data.',27);
original[3].speakerNotes.textFrame.setText('Solution, 35 seconds. The Excel file is a classification database. It contains Instructions, ASTM 1997 and ASTM 2015 sheets. Use one reference edition consistently. Automated classification comparisons and write-back are development targets. Geometry, context and properties help distinguish similar categories, such as interior and exterior doors. The workbook does not itself provide dimensional, fire-safety or accessibility requirements. Source: assets/ASTM-UniFormat.xlsx.');
const {slide:visual}=p.slides.insert({after:original[3]});visual.background.fill='#000000';txt(visual,'Use case: a window has the wrong label',41,30,1198,80,46);
visual.images.add({blob:await fs.readFile(root+'/assets/forma-classification-example.png'),contentType:'image/png',alt:'User-supplied architectural classification example showing a window mislabeled as exterior walls and a suggested exterior-window classification',fit:'contain',position:{left:20,top:135,width:1240,height:526}});
txt(visual,'Illustrative workflow in development. Classification compliance supports model-data review.',41,668,1170,30,18);
visual.speakerNotes.textFrame.setText('Main example, 45 seconds. The selected object is an exterior window. In this illustrative scenario its model label is B2010, Exterior Walls. The workbook lists B2020, Exterior Windows, on ASTM 2015 row 195. Forma is intended to present the mismatch and propose a classification for designer review. This image is supplied by the user and represents a concept, not a detected issue in the sample IFC. Source: ASTM-UniFormat.xlsx ASTM 2015 A186:B186 and A195:B195; user-supplied visual. Classification consistency does not establish building-code safety compliance.');
set(original[4],'533','Astra capabilities planned for Forma',46);
set(original[8],'4','Clearer model data\nfor construction teams',68);set(original[8],'5','Forma\nQuestions and live demo',28);
for(let i=0;i<p.slides.items.length;i++){let s=p.slides.items[i];for(let a of s.shapes.items){if(/^\d+$/.test(a.text.toString())&&a.position.top>640&&a.position.left>1100)a.text=String(i+1);}if(s===use||s===visual)txt(s,String(i+1),1200,680,45,25,16);}
const skill='/Users/me/.codex/plugins/cache/openai-primary-runtime/presentations/26.909.12148/skills/presentations';
await (await PresentationFile.exportPptx(p)).save(root+'/marketing/.build/forma-candidate.pptx');
await finalizePresentation({workspaceDir:root,candidatePath:root+'/marketing/.build/forma-candidate.pptx',finalPath:root+'/assets/Forma-Project-Demo.pptx',pythonExecutable:'/Users/me/.cache/codex-runtimes/codex-primary-runtime/dependencies/python/bin/python3',integrityValidatorPath:skill+'/container_tools/inspect_presentation_package_integrity.py',layoutValidatorPath:skill+'/container_tools/inspect_presentation_layout_geometry.py',layoutArgs:['--expected-slide-size-emu','12192000,6858000','--validate-heading-fit'],verifyArtifactToolImport:true,receiptPath:root+'/marketing/.build/forma-validation.json'});
for(let i=0;i<p.slides.items.length;i++)await fs.writeFile(`forma-slide-${i+1}.png`,new Uint8Array(await (await p.slides.items[i].export({format:'png',scale:1})).arrayBuffer()));
